// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.9
// source: proto/tariff/tariff.proto

package tariff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckIsSupportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderDestinationId    int64  `protobuf:"varint,1,opt,name=sender_destination_id,json=senderDestinationId,proto3" json:"sender_destination_id,omitempty"`
	RecipientDestinationId int64  `protobuf:"varint,2,opt,name=recipient_destination_id,json=recipientDestinationId,proto3" json:"recipient_destination_id,omitempty"`
	Shipping               string `protobuf:"bytes,3,opt,name=shipping,proto3" json:"shipping,omitempty"`
}

func (x *CheckIsSupportRequest) Reset() {
	*x = CheckIsSupportRequest{}
	mi := &file_proto_tariff_tariff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIsSupportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsSupportRequest) ProtoMessage() {}

func (x *CheckIsSupportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tariff_tariff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsSupportRequest.ProtoReflect.Descriptor instead.
func (*CheckIsSupportRequest) Descriptor() ([]byte, []int) {
	return file_proto_tariff_tariff_proto_rawDescGZIP(), []int{0}
}

func (x *CheckIsSupportRequest) GetSenderDestinationId() int64 {
	if x != nil {
		return x.SenderDestinationId
	}
	return 0
}

func (x *CheckIsSupportRequest) GetRecipientDestinationId() int64 {
	if x != nil {
		return x.RecipientDestinationId
	}
	return 0
}

func (x *CheckIsSupportRequest) GetShipping() string {
	if x != nil {
		return x.Shipping
	}
	return ""
}

type CheckIsSupportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSupport bool `protobuf:"varint,1,opt,name=is_support,json=isSupport,proto3" json:"is_support,omitempty"`
}

func (x *CheckIsSupportResponse) Reset() {
	*x = CheckIsSupportResponse{}
	mi := &file_proto_tariff_tariff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIsSupportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsSupportResponse) ProtoMessage() {}

func (x *CheckIsSupportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tariff_tariff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsSupportResponse.ProtoReflect.Descriptor instead.
func (*CheckIsSupportResponse) Descriptor() ([]byte, []int) {
	return file_proto_tariff_tariff_proto_rawDescGZIP(), []int{1}
}

func (x *CheckIsSupportResponse) GetIsSupport() bool {
	if x != nil {
		return x.IsSupport
	}
	return false
}

type RegisterCashbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RegisterCashbackRequest) Reset() {
	*x = RegisterCashbackRequest{}
	mi := &file_proto_tariff_tariff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCashbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCashbackRequest) ProtoMessage() {}

func (x *RegisterCashbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tariff_tariff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCashbackRequest.ProtoReflect.Descriptor instead.
func (*RegisterCashbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_tariff_tariff_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterCashbackRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_tariff_tariff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tariff_tariff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_tariff_tariff_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_tariff_tariff_proto protoreflect.FileDescriptor

var file_proto_tariff_tariff_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2f, 0x74,
	0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x61, 0x72,
	0x69, 0x66, 0x66, 0x22, 0xa1, 0x01, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x73, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a,
	0x15, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x38, 0x0a, 0x18, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x16, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x37, 0x0a, 0x16, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x73, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x22, 0x32, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x61, 0x73, 0x68,
	0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xb1, 0x01, 0x0a, 0x0d, 0x54, 0x61, 0x72, 0x69, 0x66,
	0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x6c, 0x61, 0x74, 0x12, 0x1d, 0x2e, 0x74,
	0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x73, 0x53, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x61,
	0x72, 0x69, 0x66, 0x66, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x73, 0x53, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x18, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x61, 0x73, 0x68, 0x62, 0x61, 0x63, 0x6b, 0x53,
	0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x61, 0x73, 0x68, 0x62, 0x61, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x74, 0x61, 0x72, 0x69, 0x66,
	0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_tariff_tariff_proto_rawDescOnce sync.Once
	file_proto_tariff_tariff_proto_rawDescData = file_proto_tariff_tariff_proto_rawDesc
)

func file_proto_tariff_tariff_proto_rawDescGZIP() []byte {
	file_proto_tariff_tariff_proto_rawDescOnce.Do(func() {
		file_proto_tariff_tariff_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tariff_tariff_proto_rawDescData)
	})
	return file_proto_tariff_tariff_proto_rawDescData
}

var file_proto_tariff_tariff_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tariff_tariff_proto_goTypes = []any{
	(*CheckIsSupportRequest)(nil),   // 0: tariff.CheckIsSupportRequest
	(*CheckIsSupportResponse)(nil),  // 1: tariff.CheckIsSupportResponse
	(*RegisterCashbackRequest)(nil), // 2: tariff.RegisterCashbackRequest
	(*Response)(nil),                // 3: tariff.Response
}
var file_proto_tariff_tariff_proto_depIdxs = []int32{
	0, // 0: tariff.TariffService.CheckSupportFlat:input_type -> tariff.CheckIsSupportRequest
	2, // 1: tariff.TariffService.RegisterCashbackShipment:input_type -> tariff.RegisterCashbackRequest
	1, // 2: tariff.TariffService.CheckSupportFlat:output_type -> tariff.CheckIsSupportResponse
	3, // 3: tariff.TariffService.RegisterCashbackShipment:output_type -> tariff.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tariff_tariff_proto_init() }
func file_proto_tariff_tariff_proto_init() {
	if File_proto_tariff_tariff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tariff_tariff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tariff_tariff_proto_goTypes,
		DependencyIndexes: file_proto_tariff_tariff_proto_depIdxs,
		MessageInfos:      file_proto_tariff_tariff_proto_msgTypes,
	}.Build()
	File_proto_tariff_tariff_proto = out.File
	file_proto_tariff_tariff_proto_rawDesc = nil
	file_proto_tariff_tariff_proto_goTypes = nil
	file_proto_tariff_tariff_proto_depIdxs = nil
}
