// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.9
// source: proto/tariff/tariff.proto

package tariff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TariffService_CheckSupportFlat_FullMethodName         = "/tariff.TariffService/CheckSupportFlat"
	TariffService_RegisterCashbackShipment_FullMethodName = "/tariff.TariffService/RegisterCashbackShipment"
)

// TariffServiceClient is the client API for TariffService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TariffServiceClient interface {
	CheckSupportFlat(ctx context.Context, in *CheckIsSupportRequest, opts ...grpc.CallOption) (*CheckIsSupportResponse, error)
	RegisterCashbackShipment(ctx context.Context, in *RegisterCashbackRequest, opts ...grpc.CallOption) (*Response, error)
}

type tariffServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTariffServiceClient(cc grpc.ClientConnInterface) TariffServiceClient {
	return &tariffServiceClient{cc}
}

func (c *tariffServiceClient) CheckSupportFlat(ctx context.Context, in *CheckIsSupportRequest, opts ...grpc.CallOption) (*CheckIsSupportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckIsSupportResponse)
	err := c.cc.Invoke(ctx, TariffService_CheckSupportFlat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tariffServiceClient) RegisterCashbackShipment(ctx context.Context, in *RegisterCashbackRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TariffService_RegisterCashbackShipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TariffServiceServer is the server API for TariffService service.
// All implementations must embed UnimplementedTariffServiceServer
// for forward compatibility.
type TariffServiceServer interface {
	CheckSupportFlat(context.Context, *CheckIsSupportRequest) (*CheckIsSupportResponse, error)
	RegisterCashbackShipment(context.Context, *RegisterCashbackRequest) (*Response, error)
	mustEmbedUnimplementedTariffServiceServer()
}

// UnimplementedTariffServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTariffServiceServer struct{}

func (UnimplementedTariffServiceServer) CheckSupportFlat(context.Context, *CheckIsSupportRequest) (*CheckIsSupportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckSupportFlat not implemented")
}
func (UnimplementedTariffServiceServer) RegisterCashbackShipment(context.Context, *RegisterCashbackRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCashbackShipment not implemented")
}
func (UnimplementedTariffServiceServer) mustEmbedUnimplementedTariffServiceServer() {}
func (UnimplementedTariffServiceServer) testEmbeddedByValue()                       {}

// UnsafeTariffServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TariffServiceServer will
// result in compilation errors.
type UnsafeTariffServiceServer interface {
	mustEmbedUnimplementedTariffServiceServer()
}

func RegisterTariffServiceServer(s grpc.ServiceRegistrar, srv TariffServiceServer) {
	// If the following call pancis, it indicates UnimplementedTariffServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TariffService_ServiceDesc, srv)
}

func _TariffService_CheckSupportFlat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIsSupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TariffServiceServer).CheckSupportFlat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TariffService_CheckSupportFlat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TariffServiceServer).CheckSupportFlat(ctx, req.(*CheckIsSupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TariffService_RegisterCashbackShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCashbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TariffServiceServer).RegisterCashbackShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TariffService_RegisterCashbackShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TariffServiceServer).RegisterCashbackShipment(ctx, req.(*RegisterCashbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TariffService_ServiceDesc is the grpc.ServiceDesc for TariffService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TariffService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tariff.TariffService",
	HandlerType: (*TariffServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckSupportFlat",
			Handler:    _TariffService_CheckSupportFlat_Handler,
		},
		{
			MethodName: "RegisterCashbackShipment",
			Handler:    _TariffService_RegisterCashbackShipment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tariff/tariff.proto",
}
